/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddEntryModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/ViewEntryModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/emojiToText`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useAuth`; params?: Router.UnknownInputParams; } | { pathname: `/types/Note`; params?: Router.UnknownInputParams; } | { pathname: `/utils/formatDate`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AddEntryModal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ViewEntryModal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/emojiToText`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useAuth`; params?: Router.UnknownOutputParams; } | { pathname: `/types/Note`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/formatDate`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calendar${`?${string}` | `#${string}` | ''}` | `/calendar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/components/AddEntryModal${`?${string}` | `#${string}` | ''}` | `/components/ViewEntryModal${`?${string}` | `#${string}` | ''}` | `/components/emojiToText${`?${string}` | `#${string}` | ''}` | `/hooks/useAuth${`?${string}` | `#${string}` | ''}` | `/types/Note${`?${string}` | `#${string}` | ''}` | `/utils/formatDate${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddEntryModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/ViewEntryModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/emojiToText`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useAuth`; params?: Router.UnknownInputParams; } | { pathname: `/types/Note`; params?: Router.UnknownInputParams; } | { pathname: `/utils/formatDate`; params?: Router.UnknownInputParams; };
    }
  }
}
